### ISSUE TITLE
ActionMenuView.java line 643

### ISSUE THREAD

**Issue by elan-ev-crashlytics** [elan-ev/StudIPAndroidApp#102]
#### in android.support.v7.widget.ActionMenuView.getMenu

* Number of crashes: 8
* Impacted devices: 8

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/56175a5ff5d3a7f76ba9fdd5](https://fabric.io/elanev/android/apps/de.elanev.studip.android.app/issues/56175a5ff5d3a7f76ba9fdd5)

**Comment by mndfcked** [comment]
This error is caused by some (mostly Samsung) devices that bundle an old version of AppCompat that interferse with the the newest one. There was a fix for AppCompat v21, but the error resurfaced with AppCompat v23 and there is currently no fix.
The issue is tracked under https://code.google.com/p/android/issues/detail?id=78377

**Comment by mndfcked** [comment]
After some a year of begging, the Android devs decided to fix the issue. In an upcoming release. https://code.google.com/p/android/issues/detail?id=78377#c270
