### ISSUE TITLE
Please publish the app on F-Droid!

### ISSUE THREAD

**Issue by conrad-heimbold** [elan-ev/StudIPAndroidApp#136]
Could you please publish this app also on F-Droid (and not only on Google Play) and get in contact with them? 
F-Droid is an Android Platform which **only** distributes 
- open source, 
- free (GNU GPL / Apache / MIT / LGPL / etc.) and
- privacy-aware / non-tracking 
Android applications. 
The source code is also thoroughly checked by the F-Droid maintainers, so that no malware can be published on F-Droid. 

You can find help on how to publish your app on F-Droid here: 
https://f-droid.org/wiki/page/FAQ_-_App_Developers
https://f-droid.org/wiki/page/Inclusion_How-To 

I already posted in the submission queue of F-Droid here: https://f-droid.org/forums/topic/stud-ip-android-app/  

Otherwise, if you do not want to publish your app there, could you maybe instead make an own repository with StudIP or Android for the F-Droid app? 

Thank you very much for your hard work!

**Comment by krt16s** [comment]
If https://github.com/elan-ev/StudIPAndroidApp/issues/14#issuecomment-40109462 is still correct, the app has to be tailored for each university or include multiple options to connect to (which still would require the credentials).

@mndfcked Is this sill the case or is the list freely available by now?

**Comment by corny2** [comment]
As far as I understand, everyone who has got a rooted android smartphone could read out the secret key that encrypts the OAuth credentials which are required to access the Stud.IP-PlugIn -servers at the different servers, am I right? So I do not really understand why this encryption is required? This is obfuscation; but offers no real protection!

**Comment by mndfcked** [comment]
We already debated a F-Droid release, and we would really like to do this. But currently it's simply not possible because we can't put all the OAuth credentials on here (which would be required for F-Droid) otherwise the list of universities would be empty. 
@corny2 you're right we obfuscate the encryption key as well as the credentials. The Android attacker model doesn't consider an attacker with root access to the device, so do we. That's why everyone with the right knowledge could extract the credentials. Sadly there is currently no other way to secure them on Android and keep the compatibility with older versions. 
@krt16s It's correct in that we pull in the credentials at release time, but the App is not tailored for each university. Sadly we are not allowed to release the credentials list. Currently the only way to create a full F-Droid compatible release is to ask every university to allow us to push their OAuth credentials to Github. And I doubt that any would agree to that. Most of them are very privacy minded. I've been looking into ways to pull the credentials at run time from a server, but we would have the same problem securing the connection in an F-Droid compatible way.
If any of you has an idea on how to solve this issue, I would love to hear about it. I'll keep this ticket open for discussion.

**Comment by corny2** [comment]
Would it be possible to program the app in a way that you can import the OAuth credentials **after** the app has been installed? I could make a fork of StudIPAndroidApp for that and then you would just have to ask your local university for the credentials. The credentials could also be saved like the wifi passwords on Android: Once you have told Android the correct WiFi passwords, you can not read them out again without root.

**Comment by mndfcked** [comment]
We already considered this option, but currently it's not worth the hassle. No user would ask the university for OAuth credentials and I doubt most unis would want to give every student their own OAuth credentials. We mostly get ours through trusted relationships to the universities maintainers. And even then it's sometimes a lot of work to get them.
The encrypted storage isn't the problem. Of course we could ask the user for a password and encrypt the credentials with it, there are multiple options to do this in a backward compatible way (The Wifi password storage has no public API). But the point is that we have to consider the user as an attacker. (When we ship the credentials)
If you want to contribute said import option, feel free to make a fork.

**Comment by corny2** [comment]
I have to correct myself: you do not even have to have a rooted smartphone; because you can make backups of APKs without root access (e.g. with Amaze). AFAIK, the necessary OAuth credentials are stored somewhere (in one of the binary files, classes.dex or icudt46l.bat?) in the APK file, although already compiled.

**Comment by mndfcked** [comment]
Of course you can get the apk file without root. For example simply with adb. Everyone can do it. The thing is, the dex is in bytecode and obfuscated. Getting the stuff from the bytecode and deobfuscate it is the hard part. As I mentioned, with enough knowledge still possible. We are aware of this, and sadly that is the current Android security model. But let me shoot a warning here.. If you try to get the credentials out the apk, and try to use them in your own app, we will fill a lawsuit. We are obligated to secure these credentials as good as possible and only we have the permission to use them in the app. If you want to make your own fork, you have to got to the Universities by yourself and ask them for the credentials as well as for the distribution permission.
